#pragma once

#include <vector>
#include <chrono>
#include <random>
#include "geometry/model/Point_2.h"
#include "geometry/model/Segment_2.h"


namespace geometry
{
#define clock std::chrono::system_clock
#define time_seed (clock::now().time_since_epoch().count() % 1000000)

	/*!
	 * A Number_generator will generate random numbers using a normal
	 * distribution. A seed can be provided to the constructor, by default it is
	 * determined by the clock
	 */
	template<typename real>
	class Number_generator
	{
		typedef double dist_number;

	public:
		explicit Number_generator(unsigned long seed = time_seed);

		/**
		 * @return a number following a normal distribution on [inf, sup]
		 */
		real next_number(const dist_number& inf = -50,
						 const dist_number& sup = 50);

	private:
		std::default_random_engine generator;
		std::normal_distribution<dist_number> distribution;
	};

	/*!
	 * @return a random Point_2 generated by ng
	 */
	template<typename real>
	Point_2<real> random_point_2(Number_generator<real>& ng);
	/*!
	 * @return a random Segment_2 generated by ng
	 */
	template<typename real>
	Segment_2<real> random_segment_2(Number_generator<real>& ng);
	/*!
	 * @return a random Point_2 vector generated by ng
	 */
	template<typename real>
	std::vector<Point_2<real>>
	random_point_2_set(unsigned n,
					   Number_generator<real>& ng);
	/*!
	 * @return a random Segment_2 vector generated by ng
	 */
	template<typename real>
	std::vector<Segment_2<real>>
	random_segment_2_set(unsigned n,
						 Number_generator<real>& ng);


	// +-----------------------------------------------------------------------+
	// |                         TEMPLATE DEFINITIONS                          |
	// +-----------------------------------------------------------------------+

	template<typename real>
	Number_generator<real>::Number_generator(unsigned long seed):
			generator(std::default_random_engine(seed)),
			distribution(std::normal_distribution<dist_number>(0, 1))
	{}

	template<typename real>
	real Number_generator<real>::next_number(const dist_number& inf,
											 const dist_number& sup)
	{
		dist_number a = distribution(generator);
		return real(inf + a * (sup - inf));
	}

	template<typename real>
	Point_2<real> random_point_2(Number_generator<real>& ng)
	{
		real x = ng.next_number();
		real y = ng.next_number();
		return Point_2<real>(x, y);
	}

	template<typename real>
	Segment_2<real> random_segment_2(Number_generator<real>& ng)
	{
		Point_2<real> p1 = random_point_2(ng);
		Point_2<real> p2 = random_point_2(ng);
		return Segment_2<real>(p1, p2);
	}

	template<typename real>
	std::vector<Point_2<real>>
	random_point_2_set(unsigned n,
					   Number_generator<real>& ng)
	{
		std::vector<Point_2<real>> points;
		for (unsigned i = 0; i < n; ++i)
		{
			points.push_back(random_point_2<real>(ng));
		}
		return points;
	}

	template<typename real>
	std::vector<Segment_2<real>>
	random_segment_2_set(unsigned n,
						 Number_generator<real>& ng)
	{
		std::vector<Segment_2<real>> segments;
		for (unsigned i = 0; i < n; ++i)
		{
			segments.push_back(random_segment_2<real>(ng));
		}
		return segments;
	}
}